# Generated by Django 4.1.7 on 2023-03-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTM_app', '0002_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='isRecmomended',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Recommended'),
        ),
        migrations.AddField(
            model_name='movie',
            name='isTopTen',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Top 10'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Rating'),
        ),
    ]
