# Generated by Django 4.1.7 on 2023-03-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YTM_app', '0003_movie_isrecmomended_movie_istopten_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='isRecmomended',
            new_name='isRecommended',
        ),
    ]
