# Generated by Django 4.1.7 on 2023-03-29 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YTM_app', '0004_rename_isrecmomended_movie_isrecommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(limit_choices_to={'id__lt': 4}, to='YTM_app.genre'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTM_app.actor')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTM_app.character')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YTM_app.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='YTM_app.Role', to='YTM_app.actor'),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshots',
            field=models.ManyToManyField(blank=True, to='YTM_app.screenshot'),
        ),
    ]
