# Generated by Django 4.1.7 on 2023-03-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YTM_app', '0006_alter_screenshot_moviename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='moviename',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='movieFrom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='YTM_app.movie'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='img',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='URL'),
        ),
    ]
