# Generated by Django 4.1.7 on 2023-03-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YTM_app', '0007_remove_screenshot_moviename_screenshot_moviefrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='altText',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Alternative Text'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='YTM_app.genre'),
        ),
    ]
